### ISSUE TITLE
Preferences dialog empty

### ISSUE THREAD

**Issue by wassi007** [mfat/sshpilot#676]
Since update to 4.3.0 the Preferences-dialog is empty.

Errormessage when started in shell:
sshpilot.preferences - ERROR - Failed to setup preferences: 'gi.repository.Adw' object has no attribute 'ToggleGroup'

sshpilot installed with Deb-File in Ubuntu 24.04. (TuxedoOs)

**Comment by mfat** [comment]
You need newer libadwaita 1.7 or newer. However I'll add a fallback in next version. Thanks for reporting.
